name: Deploy Lambda on Release

on:
  release:
    types:
      - published  # Runs when a release is published

jobs:
  deploy-lambda:
    uses: shubhsharma99/github-actions-workflows/.github/workflows/deploy-lambda.yml@main  # Update to your repository path
    with:
      aws-region: "us-east-1"
      s3-bucket: "my-deployment-bucket"
      lambda-function-name: "my-lambda-function"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

