name: CI - Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    uses: shubhsharma99/github-actions-workflows/.github/workflows/ci.yml@main
    with:
      aws-region: "us-east-1"
      s3-bucket: "my-react-app-bucket"
      node-version: "20"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
