name: Reusable CD - Deploy to AWS Lambda

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      s3-bucket:
        required: true
        type: string
      lambda-function-name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Deploy Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name ${{ inputs.lambda-function-name }} \
            --s3-bucket ${{ inputs.s3-bucket }} \
            --s3-key deployment-package.zip
